apiVersion: v1
data:
  cilium-policy.yaml: |-
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-cluster-policy"
    spec:
      description: "allow cluster intra cluster traffic"
      endpointSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
            - 192.168.128.0/17
    ---
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-external-policy"
    spec:
      description: "allow api server traffic"
      nodeSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
        - fromEntities:
            - all
          toPorts:
            - ports:
              - port: "6443"
kind: ConfigMap
metadata:
  name: test-cluster-cilium-policy
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: test-cluster-credentials
  namespace: default
stringData:
  apiToken: $LINODE_TOKEN
  dnsToken: $LINODE_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-test-cluster-crs-0
  namespace: default
stringData:
  linode-token-region.yaml: |-
    kind: Secret
    apiVersion: v1
    metadata:
      name: linode-token-region
      namespace: kube-system
    stringData:
      apiToken: $LINODE_TOKEN
      region: us-ord
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: test-cluster-cilium
  namespace: default
spec:
  chartName: cilium
  clusterSelector:
    matchLabels:
      cni: test-cluster-cilium
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://helm.cilium.io/
  valuesTemplate: |
    bgpControlPlane:
      enabled: true
    routingMode: native
    kubeProxyReplacement: true
    ipv4NativeRoutingCIDR: 10.0.0.0/8
    tunnelProtocol: ""
    enableIPv4Masquerade: true
    policyAuditMode: true
    hostFirewall:
      enabled: true
    extraConfig:
      allow-localhost: policy
    k8sServiceHost: {{ .InfraCluster.spec.controlPlaneEndpoint.host }}
    k8sServicePort: {{ .InfraCluster.spec.controlPlaneEndpoint.port }}
    extraArgs:
    - --nodeport-addresses=0.0.0.0/0
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: false
    k8s:
      requireIPv4PodCIDR: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
  version: 1.15.4
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: test-cluster-csi-driver-linode
  namespace: default
spec:
  chartName: linode-blockstorage-csi-driver
  clusterSelector:
    matchLabels:
      csi: test-cluster-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-blockstorage-csi-driver/
  valuesTemplate: |
    secretRef:
      name: "linode-token-region"
      apiTokenRef: "apiToken"
  version: v0.8.4
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: test-cluster-linode-cloud-controller-manager
  namespace: default
spec:
  chartName: ccm-linode
  clusterSelector:
    matchLabels:
      ccm: test-cluster-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-cloud-controller-manager/
  valuesTemplate: |
    secretRef:
      name: "linode-token-region"
    image:
      pullPolicy: IfNotPresent
  version: v0.4.14
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: test-cluster-cilium-policy
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster: test-cluster
  resources:
  - kind: ConfigMap
    name: test-cluster-cilium-policy
  strategy: Reconcile
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: test-cluster-crs-0
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      crs: test-cluster-crs
  resources:
  - kind: Secret
    name: linode-test-cluster-crs-0
  strategy: Reconcile
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: test-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data.label }}'
      preKubeadmCommands:
      - curl -fsSL https://github.com/linode/cluster-api-provider-linode/raw/dd76b1f979696ef22ce093d420cdbd0051a1d725/scripts/pre-kubeadminit.sh
        | bash -s v1.29.1
      - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    ccm: test-cluster-linode
    cluster: test-cluster
    cni: test-cluster-cilium
    crs: test-cluster-crs
    csi: test-cluster-linode
  name: test-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.192.0.0/10
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: test-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: LinodeCluster
    name: test-cluster
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test-cluster-md-0
  namespace: default
spec:
  clusterName: test-cluster
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: test-cluster-md-0
      clusterName: test-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeMachineTemplate
        name: test-cluster-md-0
      version: v1.29.1
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: test-cluster-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
      etcd:
        local:
          dataDir: /var/lib/etcd_data/etcd
          extraArgs:
            quota-backend-bytes: "8589934592"
    initConfiguration:
      localAPIEndpoint:
        bindPort: 6443
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.label }}'
      skipPhases:
      - addon/kube-proxy
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.label }}'
    preKubeadmCommands:
    - curl -fsSL https://github.com/linode/cluster-api-provider-linode/raw/dd76b1f979696ef22ce093d420cdbd0051a1d725/scripts/pre-kubeadminit.sh
      | bash -s v1.29.1
    - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
      kind: LinodeMachineTemplate
      name: test-cluster-control-plane
  replicas: 1
  version: v1.29.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeCluster
metadata:
  name: test-cluster
  namespace: default
spec:
  credentialsRef:
    name: test-cluster-credentials
  network:
    apiserverLoadBalancerPort: 6443
  region: us-ord
  vpcRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: LinodeVPC
    name: test-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeFirewall
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster
  name: test-cluster
  namespace: default
spec:
  credentialsRef:
    name: test-cluster-credentials
  enabled: false
  inboundPolicy: DROP
  inboundRules:
  - action: ACCEPT
    addresses:
      ipv4:
      - 10.0.0.0/8
    label: intra-cluster
    ports: 1-65535
    protocol: TCP
  - action: ACCEPT
    addresses:
      ipv4:
      - 0.0.0.0/0
      ipv6:
      - ::/0
    label: inbound-api-server
    ports: "6443"
    protocol: TCP
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: test-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      authorizedKeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6ZIrP5MEOlVsrChcdnTVutEkHG+kaNxKuC7u9J5g14fIRfyTPA56MyKxWK7H7YP6A1PGNnJwuIQiR+oE1kufHM/tfIkvXfOIipnWcPYhwFPg+H6MwaA61hpoEtnTgG7tJv5AVTDmPmPi1555zFZgJ1ndVz09vQJCQ7sM7QT8AnEBUkfIA5jbNDhd6yNDOWXeIiWT6XWbh0kLehH8VFKF9zZHp1lywH2arh5FVzdN3jJVBiefEgsT1wW1gPJlPASAFoqjIWhfPGk8R6waXVbZ7QKJ6/q+h8RH/HgrkuePsguq/1HH/wSoBBiAy4U9nMsRDf1alU382klLuNi2vjEfWl3TLj1b/wIwVMi8m1IppNqeLzw7iaz/3l5LYTjqJojHekg4xDMa7pMq11Fjak1G5TvXebMTqlHHBZjzRVpmO5fSDOtd9duanGS/I5f/F5ZVhUh4pw0uaVJTu0x5gd+IDypPZktNDBJHWaMKgKxFU+ODyS/GPo3B1ydZH1CzQJHUASqCcBv8DPTVShltoRpiS24D4r27b7vCl+rfSkEwJpKR7a6Pw4lxUyhq0YgI7TXpBJv1YmcsIhxEViAadUTMLHZB+xh4uhg92O7n1UQxieVhvTyolGjbZDcgG+6EfYPAxoQxo8teMp1quBiufR3GgV6r4Svw8WFejAVV7IBikmw== jsemaan@jsemaan-inverse
      credentialsRef:
        name: test-cluster-credentials
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: test-cluster
      image: linode/ubuntu22.04
      interfaces:
      - purpose: public
      region: us-ord
      type: g6-standard-2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: test-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      authorizedKeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6ZIrP5MEOlVsrChcdnTVutEkHG+kaNxKuC7u9J5g14fIRfyTPA56MyKxWK7H7YP6A1PGNnJwuIQiR+oE1kufHM/tfIkvXfOIipnWcPYhwFPg+H6MwaA61hpoEtnTgG7tJv5AVTDmPmPi1555zFZgJ1ndVz09vQJCQ7sM7QT8AnEBUkfIA5jbNDhd6yNDOWXeIiWT6XWbh0kLehH8VFKF9zZHp1lywH2arh5FVzdN3jJVBiefEgsT1wW1gPJlPASAFoqjIWhfPGk8R6waXVbZ7QKJ6/q+h8RH/HgrkuePsguq/1HH/wSoBBiAy4U9nMsRDf1alU382klLuNi2vjEfWl3TLj1b/wIwVMi8m1IppNqeLzw7iaz/3l5LYTjqJojHekg4xDMa7pMq11Fjak1G5TvXebMTqlHHBZjzRVpmO5fSDOtd9duanGS/I5f/F5ZVhUh4pw0uaVJTu0x5gd+IDypPZktNDBJHWaMKgKxFU+ODyS/GPo3B1ydZH1CzQJHUASqCcBv8DPTVShltoRpiS24D4r27b7vCl+rfSkEwJpKR7a6Pw4lxUyhq0YgI7TXpBJv1YmcsIhxEViAadUTMLHZB+xh4uhg92O7n1UQxieVhvTyolGjbZDcgG+6EfYPAxoQxo8teMp1quBiufR3GgV6r4Svw8WFejAVV7IBikmw== jsemaan@jsemaan-inverse
      credentialsRef:
        name: test-cluster-credentials
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: test-cluster
      image: linode/ubuntu22.04
      interfaces:
      - purpose: public
      region: us-ord
      type: g6-standard-2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeVPC
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster
  name: test-cluster
  namespace: default
spec:
  credentialsRef:
    name: test-cluster-credentials
  region: us-ord
  subnets:
  - ipv4: 10.0.0.0/8
    label: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: test-cluster-md-remote
  namespace: default
spec:
  template:
    spec:
      authorizedKeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6ZIrP5MEOlVsrChcdnTVutEkHG+kaNxKuC7u9J5g14fIRfyTPA56MyKxWK7H7YP6A1PGNnJwuIQiR+oE1kufHM/tfIkvXfOIipnWcPYhwFPg+H6MwaA61hpoEtnTgG7tJv5AVTDmPmPi1555zFZgJ1ndVz09vQJCQ7sM7QT8AnEBUkfIA5jbNDhd6yNDOWXeIiWT6XWbh0kLehH8VFKF9zZHp1lywH2arh5FVzdN3jJVBiefEgsT1wW1gPJlPASAFoqjIWhfPGk8R6waXVbZ7QKJ6/q+h8RH/HgrkuePsguq/1HH/wSoBBiAy4U9nMsRDf1alU382klLuNi2vjEfWl3TLj1b/wIwVMi8m1IppNqeLzw7iaz/3l5LYTjqJojHekg4xDMa7pMq11Fjak1G5TvXebMTqlHHBZjzRVpmO5fSDOtd9duanGS/I5f/F5ZVhUh4pw0uaVJTu0x5gd+IDypPZktNDBJHWaMKgKxFU+ODyS/GPo3B1ydZH1CzQJHUASqCcBv8DPTVShltoRpiS24D4r27b7vCl+rfSkEwJpKR7a6Pw4lxUyhq0YgI7TXpBJv1YmcsIhxEViAadUTMLHZB+xh4uhg92O7n1UQxieVhvTyolGjbZDcgG+6EfYPAxoQxo8teMp1quBiufR3GgV6r4Svw8WFejAVV7IBikmw== jsemaan@jsemaan-inverse
      credentialsRef:
        name: test-cluster-credentials
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: test-cluster
      image: linode/ubuntu22.04
      interfaces:
      - purpose: public
      region: us-mia
      type: g6-standard-2
      vpcRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeVPC
        name: test-cluster-remote
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeVPC
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test-cluster
  name: test-cluster-remote
  namespace: default
spec:
  credentialsRef:
    name: test-cluster-credentials
  region: us-mia
  subnets:
  - ipv4: 10.0.0.0/8
    label: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test-cluster-md-remote
  namespace: default
spec:
  clusterName: test-cluster
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: test-cluster-md-0
      clusterName: test-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeMachineTemplate
        name: test-cluster-md-remote
      version: v1.29.1
