apiVersion: v1
data:
  cilium-policy.yaml: |-
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-cluster-policy"
    spec:
      description: "allow cluster intra cluster traffic"
      endpointSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
            - 192.168.128.0/17
    ---
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-external-policy"
    spec:
      description: "allow api server traffic"
      nodeSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
        - fromEntities:
            - all
          toPorts:
            - ports:
              - port: "6443"
kind: ConfigMap
metadata:
  name: geo-cluster-gecko-cilium-policy
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: geo-cluster-gecko-credentials
  namespace: default
stringData:
  apiToken: $LINODE_TOKEN
  dnsToken: $LINODE_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-geo-cluster-gecko-crs-0
  namespace: default
stringData:
  linode-token-region.yaml: |-
    kind: Secret
    apiVersion: v1
    metadata:
      name: linode-token-region
      namespace: kube-system
    stringData:
      apiToken: $LINODE_TOKEN
      region: us-ord
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: geo-cluster-gecko-cilium
  namespace: default
spec:
  chartName: cilium
  clusterSelector:
    matchLabels:
      cni: geo-cluster-gecko-cilium
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://helm.cilium.io/
  valuesTemplate: |
    bgpControlPlane:
      enabled: true
    routingMode: native
    kubeProxyReplacement: true
    ipv4NativeRoutingCIDR: 10.0.0.0/8
    tunnelProtocol: ""
    enableIPv4Masquerade: true
    policyAuditMode: true
    hostFirewall:
      enabled: true
    extraConfig:
      allow-localhost: policy
    k8sServiceHost: {{ .InfraCluster.spec.controlPlaneEndpoint.host }}
    k8sServicePort: {{ .InfraCluster.spec.controlPlaneEndpoint.port }}
    extraArgs:
    - --nodeport-addresses=0.0.0.0/0
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: false
    k8s:
      requireIPv4PodCIDR: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
  version: 1.15.4
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: geo-cluster-gecko-csi-driver-linode
  namespace: default
spec:
  chartName: linode-blockstorage-csi-driver
  clusterSelector:
    matchLabels:
      csi: geo-cluster-gecko-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-blockstorage-csi-driver/
  valuesTemplate: |
    secretRef:
      name: "linode-token-region"
      apiTokenRef: "apiToken"
  version: v0.8.4
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: geo-cluster-gecko-linode-cloud-controller-manager
  namespace: default
spec:
  chartName: ccm-linode
  clusterSelector:
    matchLabels:
      ccm: geo-cluster-gecko-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-cloud-controller-manager/
  valuesTemplate: |
    secretRef:
      name: "linode-token-region"
    image:
      repository: julsemaan/linode-cloud-controller-manager
      tag: canary
      pullPolicy: Always
  version: v0.4.16
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: geo-cluster-gecko-cilium-policy
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster: geo-cluster-gecko
  resources:
  - kind: ConfigMap
    name: geo-cluster-gecko-cilium-policy
  strategy: Reconcile
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: geo-cluster-gecko-crs-0
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      crs: geo-cluster-gecko-crs
  resources:
  - kind: Secret
    name: linode-geo-cluster-gecko-crs-0
  strategy: Reconcile
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: geo-cluster-gecko-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data.label }}'
      preKubeadmCommands:
      - curl -fsSL https://github.com/linode/cluster-api-provider-linode/raw/dd76b1f979696ef22ce093d420cdbd0051a1d725/scripts/pre-kubeadminit.sh
        | bash -s v1.29.1
      - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    ccm: geo-cluster-gecko-linode
    cluster: geo-cluster-gecko
    cni: geo-cluster-gecko-cilium
    crs: geo-cluster-gecko-crs
    csi: geo-cluster-gecko-linode
  name: geo-cluster-gecko
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: geo-cluster-gecko-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: LinodeCluster
    name: geo-cluster-gecko
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: geo-cluster-gecko-md-0
  namespace: default
spec:
  clusterName: geo-cluster-gecko
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: geo-cluster-gecko-md-0
      clusterName: geo-cluster-gecko
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeMachineTemplate
        name: geo-cluster-gecko-md-0
      version: v1.29.1
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: geo-cluster-gecko-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
      etcd:
        local:
          dataDir: /var/lib/etcd_data/etcd
          extraArgs:
            quota-backend-bytes: "8589934592"
    initConfiguration:
      localAPIEndpoint:
        bindPort: 6443
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.label }}'
      skipPhases:
      - addon/kube-proxy
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.label }}'
    preKubeadmCommands:
    - curl -fsSL https://github.com/linode/cluster-api-provider-linode/raw/dd76b1f979696ef22ce093d420cdbd0051a1d725/scripts/pre-kubeadminit.sh
      | bash -s v1.29.1
    - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
      kind: LinodeMachineTemplate
      name: geo-cluster-gecko-control-plane
  replicas: 3
  version: v1.29.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeCluster
metadata:
  name: geo-cluster-gecko
  namespace: default
spec:
  credentialsRef:
    name: geo-cluster-gecko-credentials
  network:
    apiserverLoadBalancerPort: 6443
  region: us-ord
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeFirewall
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: geo-cluster-gecko
  name: geo-cluster-gecko
  namespace: default
spec:
  credentialsRef:
    name: geo-cluster-gecko-credentials
  enabled: true
  inboundPolicy: DROP
  inboundRules:
  - action: ACCEPT
    addresses:
      ipv4:
      - 10.0.0.0/8
    label: intra-cluster
    ports: 1-65535
    protocol: TCP
  - action: ACCEPT
    addresses:
      ipv4:
      - 172.234.27.117/32
    label: inbound-ssh
    ports: "22"
    protocol: TCP
  - action: ACCEPT
    addresses:
      ipv4:
      - 192.168.255.0/24
    label: inbound-api-server
    ports: "6443,8132,8133,8134,30000-32767"
    protocol: TCP
  # curl https://geoip.linode.com/ | egrep 'Chicago|Houston'  | grep -oP '^.+?,' | grep -v '::' | sed 's/,//g' | sed 's/^/      - /' > /tmp/tmp
  - action: ACCEPT
    addresses:
      ipv4:
      - 172.232.0.0/24
      - 172.232.1.0/24
      - 172.232.2.0/24
      - 172.232.3.0/24
      - 172.232.4.0/24
      - 172.232.5.0/24
      - 172.232.6.0/24
      - 172.232.7.0/24
      - 172.232.8.0/24
      - 172.232.9.0/24
      - 172.232.10.0/24
      - 172.232.11.0/24
      - 172.232.12.0/24
      - 172.232.13.0/24
      - 172.232.14.0/24
      - 172.232.15.0/24
      - 172.232.20.0/24
      - 172.232.21.0/24
      - 172.232.22.0/24
      - 172.232.23.0/24
      - 172.232.24.0/24
      - 172.232.25.0/24
      - 172.232.26.0/24
      - 172.232.27.0/24
      - 172.232.28.0/24
      - 172.232.29.0/24
      - 172.232.30.0/24
      - 172.232.31.0/24
      - 172.233.208.0/24
      - 172.233.209.0/24
      - 172.233.211.0/24
      - 172.233.212.0/24
      - 172.233.213.0/24
      - 172.233.214.0/24
      - 172.233.215.0/24
      - 172.233.216.0/24
      - 172.233.217.0/24
      - 172.233.218.0/24
      - 172.233.219.0/24
      - 172.233.220.0/24
      - 172.233.221.0/24
      - 172.233.222.0/24
      - 172.233.223.0/24
      - 172.234.16.0/24
      - 172.234.17.0/24
      - 172.234.18.0/24
      - 172.234.19.0/24
      - 172.234.20.0/24
      - 172.234.21.0/24
      - 172.234.22.0/24
      - 172.234.23.0/24
      - 172.234.24.0/24
      - 172.234.25.0/24
      - 172.234.26.0/24
      - 172.234.27.0/24
      - 172.234.28.0/24
      - 172.234.29.0/24
      - 172.234.30.0/24
      - 172.234.31.0/24
      - 172.234.192.0/24
      - 172.234.193.0/24
      - 172.234.194.0/24
      - 172.234.195.0/24
      - 172.234.196.0/24
      - 172.234.197.0/24
      - 172.234.198.0/24
      - 172.234.199.0/24
      - 172.234.200.0/24
      - 172.234.201.0/24
      - 172.234.202.0/24
      - 172.234.203.0/24
      - 172.234.204.0/24
      - 172.234.205.0/24
      - 172.234.206.0/24
      - 172.234.207.0/24
      - 172.234.212.0/24
      - 172.234.213.0/24
      - 172.234.214.0/24
      - 172.234.215.0/24
      - 172.234.216.0/24
      - 172.234.217.0/24
      - 172.234.218.0/24
      - 172.234.219.0/24
      - 172.234.220.0/24
      - 172.234.221.0/24
      - 172.234.222.0/24
      - 172.234.223.0/24
      - 172.235.112.0/24
      - 172.236.96.0/24
      - 172.236.97.0/24
      - 172.236.98.0/24
      - 172.236.99.0/24
      - 172.236.100.0/24
      - 172.236.101.0/24
      - 172.236.102.0/24
      - 172.236.103.0/24
      - 172.236.104.0/24
      - 172.236.105.0/24
      - 172.236.106.0/24
      - 172.236.107.0/24
      - 172.236.108.0/24
      - 172.236.109.0/24
      - 172.236.110.0/24
      - 172.236.111.0/24
      - 172.236.112.0/24
      - 172.236.113.0/24
      - 172.236.114.0/24
      - 172.236.115.0/24
      - 172.236.116.0/24
      - 172.236.117.0/24
      - 172.236.118.0/24
      - 172.236.119.0/24
      - 172.236.120.0/24
      - 172.236.121.0/24
      - 172.236.122.0/24
      - 172.236.123.0/24
      - 172.236.124.0/24
      - 172.236.125.0/24
      - 172.236.126.0/24
      - 172.236.127.0/24
      - 172.232.16.0/24
      - 172.232.17.0/24
      - 172.232.18.0/24
      - 172.232.19.0/24
      - 172.234.208.0/24
      - 172.234.209.0/24
      - 172.234.210.0/24
      - 172.234.211.0/24
      - 172.233.210.0/24
    label: inbound-wireguard
    ports: "8172"
    protocol: UDP
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: geo-cluster-gecko-control-plane
  namespace: default
spec:
  template:
    spec:
      authorizedKeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6ZIrP5MEOlVsrChcdnTVutEkHG+kaNxKuC7u9J5g14fIRfyTPA56MyKxWK7H7YP6A1PGNnJwuIQiR+oE1kufHM/tfIkvXfOIipnWcPYhwFPg+H6MwaA61hpoEtnTgG7tJv5AVTDmPmPi1555zFZgJ1ndVz09vQJCQ7sM7QT8AnEBUkfIA5jbNDhd6yNDOWXeIiWT6XWbh0kLehH8VFKF9zZHp1lywH2arh5FVzdN3jJVBiefEgsT1wW1gPJlPASAFoqjIWhfPGk8R6waXVbZ7QKJ6/q+h8RH/HgrkuePsguq/1HH/wSoBBiAy4U9nMsRDf1alU382klLuNi2vjEfWl3TLj1b/wIwVMi8m1IppNqeLzw7iaz/3l5LYTjqJojHekg4xDMa7pMq11Fjak1G5TvXebMTqlHHBZjzRVpmO5fSDOtd9duanGS/I5f/F5ZVhUh4pw0uaVJTu0x5gd+IDypPZktNDBJHWaMKgKxFU+ODyS/GPo3B1ydZH1CzQJHUASqCcBv8DPTVShltoRpiS24D4r27b7vCl+rfSkEwJpKR7a6Pw4lxUyhq0YgI7TXpBJv1YmcsIhxEViAadUTMLHZB+xh4uhg92O7n1UQxieVhvTyolGjbZDcgG+6EfYPAxoQxo8teMp1quBiufR3GgV6r4Svw8WFejAVV7IBikmw== jsemaan@jsemaan-inverse
      credentialsRef:
        name: geo-cluster-gecko-credentials
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: geo-cluster-gecko
      vpcRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeVPC
        name: geo-cluster-gecko
      image: linode/ubuntu22.04
      interfaces:
      - purpose: public
      region: us-ord
      type: g6-dedicated-2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: geo-cluster-gecko-md-0
  namespace: default
spec:
  template:
    spec:
      authorizedKeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6ZIrP5MEOlVsrChcdnTVutEkHG+kaNxKuC7u9J5g14fIRfyTPA56MyKxWK7H7YP6A1PGNnJwuIQiR+oE1kufHM/tfIkvXfOIipnWcPYhwFPg+H6MwaA61hpoEtnTgG7tJv5AVTDmPmPi1555zFZgJ1ndVz09vQJCQ7sM7QT8AnEBUkfIA5jbNDhd6yNDOWXeIiWT6XWbh0kLehH8VFKF9zZHp1lywH2arh5FVzdN3jJVBiefEgsT1wW1gPJlPASAFoqjIWhfPGk8R6waXVbZ7QKJ6/q+h8RH/HgrkuePsguq/1HH/wSoBBiAy4U9nMsRDf1alU382klLuNi2vjEfWl3TLj1b/wIwVMi8m1IppNqeLzw7iaz/3l5LYTjqJojHekg4xDMa7pMq11Fjak1G5TvXebMTqlHHBZjzRVpmO5fSDOtd9duanGS/I5f/F5ZVhUh4pw0uaVJTu0x5gd+IDypPZktNDBJHWaMKgKxFU+ODyS/GPo3B1ydZH1CzQJHUASqCcBv8DPTVShltoRpiS24D4r27b7vCl+rfSkEwJpKR7a6Pw4lxUyhq0YgI7TXpBJv1YmcsIhxEViAadUTMLHZB+xh4uhg92O7n1UQxieVhvTyolGjbZDcgG+6EfYPAxoQxo8teMp1quBiufR3GgV6r4Svw8WFejAVV7IBikmw== jsemaan@jsemaan-inverse
      credentialsRef:
        name: geo-cluster-gecko-credentials
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: geo-cluster-gecko
      vpcRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeVPC
        name: geo-cluster-gecko
      image: linode/ubuntu22.04
      interfaces:
      - purpose: public
      privateIP: false
      region: us-ord
      type: g6-dedicated-2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeVPC
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: geo-cluster-gecko
  name: geo-cluster-gecko
  namespace: default
spec:
  credentialsRef:
    name: geo-cluster-gecko-credentials
  region: us-ord
  subnets:
  - ipv4: 10.41.0.0/16
    label: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: geo-cluster-gecko-md-remote
  namespace: default
spec:
  template:
    spec:
      authorizedKeys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6ZIrP5MEOlVsrChcdnTVutEkHG+kaNxKuC7u9J5g14fIRfyTPA56MyKxWK7H7YP6A1PGNnJwuIQiR+oE1kufHM/tfIkvXfOIipnWcPYhwFPg+H6MwaA61hpoEtnTgG7tJv5AVTDmPmPi1555zFZgJ1ndVz09vQJCQ7sM7QT8AnEBUkfIA5jbNDhd6yNDOWXeIiWT6XWbh0kLehH8VFKF9zZHp1lywH2arh5FVzdN3jJVBiefEgsT1wW1gPJlPASAFoqjIWhfPGk8R6waXVbZ7QKJ6/q+h8RH/HgrkuePsguq/1HH/wSoBBiAy4U9nMsRDf1alU382klLuNi2vjEfWl3TLj1b/wIwVMi8m1IppNqeLzw7iaz/3l5LYTjqJojHekg4xDMa7pMq11Fjak1G5TvXebMTqlHHBZjzRVpmO5fSDOtd9duanGS/I5f/F5ZVhUh4pw0uaVJTu0x5gd+IDypPZktNDBJHWaMKgKxFU+ODyS/GPo3B1ydZH1CzQJHUASqCcBv8DPTVShltoRpiS24D4r27b7vCl+rfSkEwJpKR7a6Pw4lxUyhq0YgI7TXpBJv1YmcsIhxEViAadUTMLHZB+xh4uhg92O7n1UQxieVhvTyolGjbZDcgG+6EfYPAxoQxo8teMp1quBiufR3GgV6r4Svw8WFejAVV7IBikmw== jsemaan@jsemaan-inverse
      credentialsRef:
        name: geo-cluster-gecko-credentials
      firewallRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeFirewall
        name: geo-cluster-gecko
      image: linode/ubuntu22.04
      interfaces:
      - purpose: public
      privateIP: false
      region: us-hou-1
      type: g6-dedicated-edge-2
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: geo-cluster-gecko-md-remote
  namespace: default
spec:
  clusterName: geo-cluster-gecko
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: geo-cluster-gecko-md-0
      clusterName: geo-cluster-gecko
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: LinodeMachineTemplate
        name: geo-cluster-gecko-md-remote
      version: v1.29.1
